rosegarden/urls.py
from django.urls import path
from . import views

app_name = 'rosegarden'
urlpatterns = [
    path('', views.homepage, name='index'),
    path('books/', views.homepage),
    path('books/<int:book_pk>/', views.bookDetails, name='book_details'),
    path('books/<int:book_pk>/edit/', views.edit_book, name='edit_book'),
    path('books/<int:book_pk>/delete/', views.delete_book, name='delete_book'),
    path('search/', views.search, name='search'),
    path('branches/', views.branchList, name='branch_list'),
    path('branches/<int:branch_pk>', views.branchDetails, name='branch_details'),
    path('users/', views.userList, name='user_list'),
    path('users/<str:username>',views.userDetails, name='user_details'),
    path('users/<str:username>/edit/',views.userEdit, name='edit_user'),
    path('add_book/', views.add_book, name='add_book'),
    path('how_to/', views.how_to, name="how_to")
]

rosegarden/templates/rosegarden/baseTemplate.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Rose Garden Template{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
        
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&display=swap" rel="stylesheet"> 

        {% load static %}
        <link rel="stylesheet" href="{% static 'rosegarden/style.css' %}">
    
    </head>

    <body>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

        <div class="container-fluid bg-light">
        
            <div id="page_header">
                {% block page_header %}
                
                {# Load in the LOGOUT_URL from the project's settings.py #}
                {% load settings_tag %}
                {% settings_value 'LOGOUT_URL' as LOGOUT_URL %}

                {# Display the navigation bar #}
                <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                    <div class="container-fluid">

                        <a class="navbar-brand playfairfont" href="#"><i>Rose Garden Library</i></a>

                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        
                        <div class="collapse navbar-collapse" id="navbarNavDropdown">
                            <ul class="navbar-nav">
                                <li class="nav-item"><a class="nav-link ps-3" href="{% url 'rosegarden:index' %}">Home</a></li>
                                <li class="nav-item"><a class="nav-link ps-3" href="{% url 'rosegarden:search' %}">Search</a></li>
                                <li class="nav-item"><a class="nav-link ps-3" href="{% url 'rosegarden:branch_list' %}">Branch List</a></li>
                                <li class="nav-item"><a class="nav-link ps-3" href="{% url 'rosegarden:user_list' %}">User List</a></li>
                                {% if user.is_authenticated %}
                                <li class="nav-item"><a class="nav-link ps-3" href="{% url 'rosegarden:user_details' user.username %}">My User Page</a></li>
                                <li class="nav-item"><a class="nav-link ps-3" href="{% url 'rosegarden:add_book' %}">Add Book</a></li>
                                <li class="nav-item"><a class="nav-link ps-3" href="{% url LOGOUT_URL %}">Log Out</a></li>
                        {% endif %}
                            </ul>
                        </div>
                    </div>
                </nav>
                <hr>
                {% endblock page_header%}
            </div>

            <div id="content">
                {% block content%}
                Welcome to the Rose Garden!
                {% endblock content%}
            </div>

            <div id="page_footer">
                {% block page_footer%}
                <hr>
                <small>&copy; Copyright {% now "Y"%}, Benjamin Roos</small>
                {% endblock page_footer%}
            </div>

        </div>
    </body>
</html>

rosegarden/templates/rosegarden/bookAdd.html
{% extends 'rosegarden/baseTemplate.html' %}

{% block title %}Adding a new book | Rose Garden{% endblock title%}

{% block content%}
    <h2>Adding a new book to the <i>{{profile.branch.name}}</i> branch...</h2>

    <form class="border" action="{% url 'rosegarden:add_book' %}" method="post">
    <div class="m-3">

        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="fieldWrapper">
            {{ form.title.label_tag }}
            {{ form.title.errors }}
            {{ form.title }}
        </div>
        <div class="fieldWrapper">
            {{ form.author_editor.label_tag }}
            {{ form.author_editor.errors }}
            {{ form.author_editor }}
        </div>
        <div class="fieldWrapper">
            {{ form.ddc_number.label_tag }}
            {{ form.ddc_number.errors }}
            {{ form.ddc_number }}
        </div>
        <div class="fieldWrapper">
            {{ form.version.label_tag }}
            {{ form.version.errors }}
            {{ form.version }}
        </div>
        <div class="fieldWrapper">
            {{ form.is_biography_or_memoir.label_tag }}
            {{ form.is_biography_or_memoir.errors }}
            {{ form.is_biography_or_memoir }}
        </div>
        <input type="submit" class="btn btn-dark" value="Save">
    
    </div>
    </form>

    <h3 class="pt-4">Help</h3>
    <div class="border">
        <div class="m-3">

            <h4>What should I use as the Dewey Decimal Number?</h4>
            <div class="ps-3">
                <p>
                    You should be able to find the most common Dewey Decimal number for non-fiction books
                    by searching for the book at <a href="http://classify.oclc.org/classify2/">classify.oclc.org/classify2/</a><br>
                    (Search by ISBN or title/author).
                </p>

                <p>
                    Fiction, literature, and poetry can be logged under <b>800</b>.<br>
                    Biographies use <b>921</b>.
                </p>
                    When in doubt, choose the most relevant category and number below:
                    <table class="table table-striped">
                        <tr>
                            <th>Dewey Decimal Number</th>
                            <th>Category</th>
                        </tr>
                        <tr><td>000</td><td>Computer science, information &amp; general works</td></tr>
                        <tr><td>100</td><td>Philosophy &amp; psychology</td></tr>
                        <tr><td>200</td><td>Religion</td></tr>
                        <tr><td>300</td><td>Social sciences</td></tr>
                        <tr><td>400</td><td>Language</td></tr>
                        <tr><td>500</td><td>Science</td></tr>
                        <tr><td>600</td><td>Technology</td></tr>
                        <tr><td>700</td><td>Arts &amp; recreation</td></tr>
                        <tr><td>800</td><td>Literature</td></tr>
                        <tr><td>900</td><td>History &amp; geography</td></tr>
                    </table>
                <p>
            </div>

        </div>
    </div>
{% endblock content%}

rosegarden/templates/rosegarden/bookDelete.html
{% extends 'rosegarden/baseTemplate.html' %}

{% block title %}
    {% if not already_deleted %}Deleting {{ book.title }} | Rose Garden
    {% else %}Deleted Book{% endif %}
{% endblock title%}

{% block content%}
    {% if already_deleted%}
        <p>This book has been removed from the library.</p>
    {% else %}
        <h2>Deleting <i>{{ book.title }}</i></h2>
        <h4>This book will be removed from the <i>{{book.branch.name}}</i> branch...</h4>

        <p>Are you sure you want to delete this book?</p>
        <p><b>Warning:</b> This cannot be easily undone! Contact Ben with any questions. </p>

        <form action="{% url 'rosegarden:delete_book' book.pk %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" class="btn btn-dark" value="Delete Book">
        </form>
    {% endif %}

{% endblock content%}

rosegarden/templates/rosegarden/bookDetails.html
{% extends 'rosegarden/baseTemplate.html' %}

{% block title %}
    {% if not is_deleted %}{{ book.title }} | Rose Garden
    {% else %}Deleted Book{% endif %}
{% endblock title%}

{% block content%}

    {% if is_deleted %}
        <p>This book has been removed from the library.</p>
    {% else %}
        <h2><i>{{ book.title }}</i></h2>
        <h3>Available in the <i>{{book.branch.name}}</i> branch</h3>
        
        {% if can_view_edit_button %}
            <a href="{% url 'rosegarden:edit_book' book.pk %}"><button type='button' class='btn btn-dark'>Edit this book</button></a>
            <a href="{% url 'rosegarden:delete_book' book.pk %}"><button type='button' class='btn btn-dark'>Delete this book</button></a>
        {% endif %}

        <ul class="list group">
            <div class="border">
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        Title:
                        <div class="fw-bold">{{ book.title }}</div>
                    </div>
                </li>
            </div>
            
            <div class="border">
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        Author or Editor:
                        <div class="fw-bold">{{ book.author_editor}}</div>
                    </div>
                </li>
            </div>

            <div class="border">
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        Dewey Decimal Number:
                        <div class="fw-bold">{{ book.ddc_number }}</div>
                    </div>
                </li>
            </div>
                
            <div class="border">
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        Category:
                        <div class="fw-bold">{{ book.get_category }}</div>
                    </div>
                </li>
            </div>

            <div class="border">
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        Version:
                        <div class="fw-bold">{{ book.version }}</div>
                    </div>
                </li>
            </div>

            <div class="border">
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        Is this book a biography or memoir?:
                        <div class="fw-bold">{{ book.is_biography_or_memoir }}</div>
                    </div>
                </li>
            </div>
                
            <div class="border">
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        Home Branch:
                        <div class="fw-bold"><a href="{% url 'rosegarden:branch_details' book.branch.pk %}">{{ book.branch.name }}</a></div>
                    </div>
                </li>
            </div>
        </ul>
    {% endif %}

{% endblock content%}

rosegarden/templates/rosegarden/bookEdit.html
{% extends 'rosegarden/baseTemplate.html' %}

{% block title %}Editing {{ book.title }} | Rose Garden{% endblock title%}

{% block content%}
    <h2>Editing <i>{{ book.title }}</i></h2>
    <h4>As part of the <i>{{book.branch.name}}</i> branch...</h4>

    <form action="{% url 'rosegarden:edit_book' book.pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-dark" value="Save">
    </form>

{% endblock content%}

rosegarden/templates/rosegarden/branchDetails.html
{% extends 'rosegarden/baseTemplate.html' %}

{% block title %} {{ branch.name }} | Branch Details | Rose Garden {% endblock title%}

{% block content%}
    <h2>Branch details for <i>{{ branch.name }}</i></h2>

    <ul class="list-group">
        <div class="border">
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    Name:
                    <div class="fw-bold">{{ branch.name }}</div>
                </div>
            </li>
        </div>

        <div class="border">
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    Location:
                    <div class="fw-bold">{{ branch.location }}</div>
                </div>
            </li>
        </div>

        <div class="border">
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    Branch Users:
                    <div class="fw-bold">
                        <ul class="list-group">
                        {% if branch_profiles %}
                            {% for branch_profile in branch_profiles %}
                                <li class="list-group-item">
                                    <a href="{% url 'rosegarden:user_details' branch_profile.user.username %}">{{ branch_profile.user.username }}</a>
                                </li>
                            {% endfor %}
                        {% endif %}
                        </ul>
                    </div>
                </div>
            </li>
        </div>

    </ul>

{% endblock content%}

<div class="border">
    <li class="list-group-item d-flex justify-content-between align-items-start">
        <div class="ms-2 me-auto">
            Category:
            <div class="fw-bold">{{ book.get_category }}</div>
        </div>
    </li>
</div>

rosegarden/templates/rosegarden/branchList.html
{% extends 'rosegarden/baseTemplate.html' %}

{% block title %}Branches | Rose Garden{% endblock title%}

{% block content%}
    <h2>Branches in the Rose Garden Library</h2>

    <table class="table table-striped">
        <tr> {# Header Row #}
            <th>Name</th>
            <th>Location</th>
        </tr>
        {% for branch in branch_list %}
        <tr>
            <td><a href="{% url 'rosegarden:branch_details' branch.pk %}">{{ branch.name}}</a></td>
            <td>{{ branch.location }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock content%}

rosegarden/templates/rosegarden/howto.html
{% extends 'rosegarden/baseTemplate.html' %}

{% block title %}How To | Rose Garden {% endblock title%}

{% block content%}
    <div class="border m-3"><div class="m-3">
        <h2>Branches and Books</h2>
        <p>
            {% if user.is_authenticated %}As a user, you will be associated with one branch of the library. You may only create and edit books in your branch.{% endif %}
            The <a href="{% url 'rosegarden:user_list'%}">Users page</a> shows all active library users, and the
                <a href="{% url 'rosegarden:branch_list'%}">Branches page</a> shows their respective branches.
        </p>

        {% if user.is_authenticated %}
        <p>
            Use the <a href="{% url 'rosegarden:add_book'%}">Add Book</a> page to add new books to your branch! To edit or delete a book in your branch: either find the book
            on the <a href="{% url 'rosegarden:index'%}">Home page</a> listing or via the <a href="{% url 'rosegarden:search'%}">Search page</a>, click on the book,
            and then use the edit or delete buttons at the top of the page.
        </p>
        {% endif %}

        <p>
            The <a href="{% url 'rosegarden:search'%}">Search page</a> provides a quick keyword search and an advanced search to find specific books in any branch of the library.
        </p>
    </div></div>

    
    {% if user.is_authenticated %}
    <div class="border m-3"><div class="m-3">
        <h2>User Management</h2>
        <p>
            You can change your password any time on the <a href="{% url 'rosegarden:user_details' user.username %}">My User Page</a>. Contact Ben if you forget your password.
        </p>
        <p>The My User page also has a place for marking your current reading interests. Please take a moment to fill this out!</p>
    </div></div>
    {% endif %}

    <div class="border m-3"><div class="m-3">
        <h2>Other Questions, Suggestions, or Ideas?</h2>
        <p>Get in touch with Ben!</p>
    </div></div>
{% endblock content%}

rosegarden/templates/rosegarden/index.html
{% extends 'rosegarden/baseTemplate.html' %}

{% block title %}Rose Garden Library{% endblock title%}

{% block content%}

    <h2>Welcome to the Rose Garden library!</h2>

    <p class="ms-3">
        This is a place to plant beautiful works and ideas, watch the collections grow,
         and share their blossoms with each other.<br> 
        {% if book_list %}The books of the library are displayed below.{% endif %}
        Please see the <a href="{% url 'rosegarden:how_to' %}">How To</a> 
         page for guidance on using this site.
    </p>

    {% if book_list%}
        <div class="table-responsive">
            <table class="table table-responsive table-striped">
                <tr> {# Header Row #}
                    <th>Title</th>
                    <th>Author or Editor</th>
                    <th>DDC number</th>
                    <th>Category</th>
                    <th>Home Branch</th>
                </tr>
                {% for book in page_obj %}
                <tr>
                    <td><a href="{% url 'rosegarden:book_details' book.pk %}">{{ book.title }}</a></td>
                    <td>{{ book.author_editor }}</td>
                    <td>{{ book.ddc_number }}</td>
                    <td>{{ book.get_category }}</td>
                    <td>{{ book.branch.name }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>

        {% include 'rosegarden/paginator.html' %}

    {% else %}
        <p class="ms-3">There are currently no books in the library!</p>
        {% if user.is_authenticated %}<p>Create a new book on the <i>Add Book</i> page.<p>{% endif %}
    {% endif %}

{% endblock content%}

rosegarden/templates/rosegarden/paginator.html
<div class="m-3">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class="link-success" href="?page=1">&laquo; first</a>
            <a class="link-success" href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a class="link-success" href="?page={{ page_obj.next_page_number }}">next</a>
            <a class="link-success" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

rosegarden/templates/rosegarden/search.html
{% extends 'rosegarden/baseTemplate.html' %}

{% block title %}Search | Rose Garden Library{% endblock title%}

{% block content%}
    

    {% if no_results_flag %}
    <h2>No Results Found</h2>
    <hr>
    {% endif %}
    
    {% if book_list %}
        <h2>Search Results</h2>
        <div class="table-responsive">
            <table class="table table-striped">
                <tr> {# Header Row #}
                    <th>Title</th>
                    <th>Author or Editor</th>
                    <th>DDC number</th>
                    <th>Category</th>
                    <th>Home Branch</th>
                </tr>
                {% for book in book_list %}
                <tr>
                    <td><a href="{% url 'rosegarden:book_details' book.pk %}">{{ book.title }}</a></td>
                    <td>{{ book.author_editor }}</td>
                    <td>{{ book.ddc_number }}</td>
                    <td>{{ book.get_category }}</td>
                    <td>{{ book.branch.name }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>

        <hr>
    {% endif %}

    
    <h2>Quick Search</h2>
    <p class="pb-3">Keyword search in a book's title, author, version, branch, or DDC number fields.</p>
    <form class="border" action="{% url 'rosegarden:search' %}" method="get">
    <div class="m-3"
        {{ quicksearch_form.as_p }}
        <input type="submit" class="btn btn-dark" value="Search">
    </div>
    </form>
   
    <h2 class="pt-3">Advanced Search</h2>
    <p class="pb-3">The category filter takes precedence over the dewey decimal range filter if both are present.</p>
    <form class="border" action="{% url 'rosegarden:search' %}" method="get">
    <div class="m-3">

        {{ fullsearch_form.non_field_errors }}
        
        <div class="fieldWrapper">
            <p>
            {{ fullsearch_form.f.label_tag }}
            {{ fullsearch_form.f.errors }}
            {{ fullsearch_form.f }}
            </p>
        </div>

        <div class="fieldWrapper">
            <p>
            {{ fullsearch_form.title.label_tag }}
            {{ fullsearch_form.title.errors }}
            {{ fullsearch_form.title }}
            </p>
        </div>

        <div class="fieldWrapper">
            <p>
            {{ fullsearch_form.author.label_tag }}
            {{ fullsearch_form.author.errors }}
            {{ fullsearch_form.author }}
            </p>
        </div>
        

        <p>Dewey Decimal Range</p>

        <div class="row pb-4">
            <div class="col ps-5">
                {{ fullsearch_form.ddcmin.label_tag }}
                {{ fullsearch_form.ddcmin.errors }}
                {{ fullsearch_form.ddcmin }}
            </div>

            <div class="col">
                {{ fullsearch_form.ddcmax.label_tag }}
                {{ fullsearch_form.ddcmax.errors }}
                {{ fullsearch_form.ddcmax }}
            </div>
        </div>


        <div class="fieldWrapper">
            <p>
            {{ fullsearch_form.cat.label_tag }}
            {{ fullsearch_form.cat.errors }}
            {{ fullsearch_form.cat }}
            </p>
        </div>

        <div class="fieldWrapper">
            <p>
            {{ fullsearch_form.bio.label_tag }}
            {{ fullsearch_form.bio.errors }}
            {{ fullsearch_form.bio }}
            </p>
        </div>

        <div class="fieldWrapper">
            <p>
            {{ fullsearch_form.branch.label_tag }}
            {{ fullsearch_form.branch.errors }}
            {{ fullsearch_form.branch }}
            </p>
        </div>

        <input type="submit" class="btn btn-dark" value="Search">
    </div>
    </form>

{% endblock content%}

rosegarden/templates/rosegarden/userDetails.html
{% extends 'rosegarden/baseTemplate.html' %}

{% block title %} {{ username }} | User Details | Rose Garden {% endblock title%}

{% block content%}
    <h2>User details for <i>{{ username }}</i></h2>

    {% if matching_user %}
        <p>
            <b>Account Management: </b>
            <a href="{% url change_password_url %}"><button type="button" class="btn btn-dark">Click here to change your password</button></a>
        </p>
    {% endif %}

    <ul class="list group">

        <div class="border">
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    Full Name:
                    <div class="fw-bold">{{ page_user.get_full_name }}</div>
                </div>
            </li>
        </div>

        <div class="border">
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    Branch:
                    <div class="fw-bold"><a href="{% url 'rosegarden:branch_details' profile.branch.pk %}">{{ profile.branch.name }}</a></div>
                </div>
            </li>
        </div>

        <div class="border">
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    Current Reading Interests: 
                    {% if matching_user %}<a href="{% url 'rosegarden:edit_user' username %}"><button type="button" class="btn btn-dark">Edit</button></a>{% endif %}
                    <div class="fw-bold ps-5">{{ profile.interests|linebreaks }}</div>
                </div>
            </li>
        </div>

{% endblock content%}

rosegarden/templates/rosegarden/userEdit.html
{% extends 'rosegarden/baseTemplate.html' %}

{% block title %} {{ username }} | Editing Interests | Rose Garden {% endblock title%}

{% block content%}
    <h2>Editing User interests for <i>{{ username }}</i></h2>

    <form action="{% url 'rosegarden:edit_user' username %}" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <p>
            {{ form.interests.errors }}
            {{ form.interests.label_tag }}
        </p>
        <p>
            {{ form.interests }}
        </p>
        <input type="submit" class="btn btn-dark" value="Save">
    </form>

{% endblock content%}

rosegarden/templates/rosegarden/userList.html
{% extends 'rosegarden/baseTemplate.html' %}

{% block title %}Users | Rose Garden{% endblock title%}

{% block content%}
    <h2>Users in the Rose Garden</h2>

    <table class="table table-striped">
        <tr> {# Header Row #}
            <th>User Name</th>
            <th>Full Name</th>
            <th>Branch</th>
        </tr>
        {% for profile in profile_list %}
        <tr>
            <td><a href="{% url 'rosegarden:user_details' profile.user.username %}">{{ profile.user.username }}</a></td>
            <td>{{ profile.user.get_full_name }}</td>
            <td><a href="{% url 'rosegarden:branch_details' profile.branch.pk %}">{{ profile.branch.name }}</a></td>
        </tr>
        {% endfor %}
    </table>
{% endblock content%}